name: Hello World Workflow

on:
  push: 
    branches: 
      - test-branch-0

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: "Hello World Printing Step"
        shell: bash
        run: |
          echo "Hello World!!!"
      
