on:
  push:
   branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  multi-event-example:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"